### PR TITLE
Added class: temperature-programmed surface reaction spectroscopy

### LINKED ISSUE #19: [TERM REQUEST] Temperature programmed surface reaction spectroscopy
Hello, I am working on the maintenance of the eNanoMapper ontology for nanosafety, which imports chemical methods from chmo. After looking at [This](https://github.com/enanomapper/ontologies/issues/310) eNanoMapper ontology term request, I am wondering whether to add the term under spectroscopy or thermal analysis, and figured it would be good to ask here whether this is a term you want to consider adding before I make a decision.

* Label: temperature-programmed surface reaction spectroscopy
* Synonyms:  TPSR | temperature programmed surface reaction spectroscopy
* Subclass of: thermal analysis (CHMO:0000681) or spectroscopy (CHMO:0000228).
* Proposed definition of the term: Spectroscopy that uses thermal analysis to probe the surface chemistry of heterogeneous catalysts. 
    * Another proposed definition by @vedina: Temperature programmed surface reaction spectroscopy (TPSR) is a technique to determine the surface chemistry of bulk metal, supported metal, bulk metal oxide, supported metal oxide, zeolite, and molecular sieve catalysts.

(https://doi.org/10.1002/cjce.23913 for reference)
Thanks!

### PR DESCRIPTION
**Pull request by jmillanacosta**
Fixes #19

temperature-programmed surface reaction spectroscopy is a subclass of spectroscopy and of thermal analysis

### CODE REVIEW

**Comment by batchelorc** [comment]
Oh thanks for this - hadn't got round to replying. Could you regenerate/edit the .obo file so it doesn't get out of sync, please?

If not I'll have a bash later.

**Comment by jmillanacosta** [comment]
> Oh thanks for this - hadn't got round to replying. Could you regenerate/edit the .obo file so it doesn't get out of sync, please?
> 
> If not I'll have a bash later.

Done with [6294825](https://github.com/rsc-ontologies/rsc-cmo/pull/20/commits/62948251b28c30fd7f617ee32fcbd7bab5512a14), please let me know if all seems okay.

**Comment by batchelorc** [comment]
Many thanks!

**Comment by jmillanacosta** [comment]
> Many thanks!

Thank you too for your quick reply!

**Pull request merged**
